### PR TITLE
Fix replaceText IOOBE

### PR DESCRIPTION
**Pull request by Jugen**
This is a fix for #689  ArrayIndexOutOfBoundsException in `ParagraphText.getRangeShapeSafely` after calling `replaceText` under certain conditions.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Thanks for the PR!

**Comment by JordanMartinez** [comment]
I looked through the Travis CI logs and came across [these lines](https://travis-ci.org/FXMisc/RichTextFX/jobs/344826898#L2384). Is it possible to get rid of them somehow? Or is that necessary in order to run the test due to the diaereses/umlauts and just an unfortunate issue on the Mac JDK?

Also, could the test work without such a long and verbose text that otherwise obscures the issue with a lot of noise? For example, you shared that you were able to reproduce the issue (though perhaps for different reasons) using the texts:
````
Text A: "1234567890\n\nabcdefghij\n\n1234567890\n\nabcdefghij"
Text B: "1234567890\n\nabcdefghijklmno\n\n1234567890\n\nabcde"
````

**Comment by Jugen** [comment]
Yeh, I noticed that in the Travis logs as well and unfortunately I don't know if it's possible to get rid of them. As you surmised, I believe it is necessary for the reasons you mention.

I created two tests, one using the long & verbose text and the other my shorter version - since there is a subtle difference to the way the IOOBE gets triggered in each. I had another look, doing a text comparison between the two long texts and have managed to reduce it down to a much shorter version with the same properties and results as before. :-)

**Comment by JordanMartinez** [comment]
Ok. It is what it is. I'm going to merge #687 first and then I'd like to merge this one since it'll take me a lot more work to include this one in mine than to include mine in yours.

**Pull request merged**
