### PR TITLE
Added methods to preset the style of inserted text

### PR DESCRIPTION
**Pull request by Jugen**
RFE #864 How to apply style so that subsequent text uses it.

### CODE REVIEW

**Comment by garybentley** [comment]
This looks fine, however I think similar methods should be added for the paragraph style.  Consider the case where a user cut-n-pastes a chunk of text, consisting of multiple paragraphs into the area, being able to set the paragraph style(s) would be good.

**Comment by garybentley** [comment]
Just tested this change with the following code:

```
IndexRange r = this.getSelection();
TextStyle s = this.getStyleAtPosition(r.getStart() + 1);

boolean t = !s.isBold();
s.setBold (t);
this.setTextInsertionStyle(s);
```
However when I then type a single character all none explicitly styled text in the paragraph has the style applied.  In this case all the none styled text is becoming bold and then un-bold when I turn it off again.

Am I doing something wrong?

**Comment by Jugen** [comment]
I think it's because you are modifying the TextStyle object that is already associated with the text in the paragraph instead of setting a new TextStyle. If you are using a modified TextStyle from RichTextFX then try something like this:

```java
 TextStyle s = getStyleAtPosition( r.getStart() + 1 );
 TextStyle newStyleObject = s.updateWith( TextStyle.bold( ! s.isBold() ) );
 setTextInsertionStyle( newStyleObject );
```

**Comment by Jugen** [comment]
Otherwise what you effectively want is something like:

```java
 TextStyle s = getStyleAtPosition( r.getStart() + 1 );
 TextStyle newStyleObject = new TextStyle( s );
 newStyleObject.setBold( ! s.isBold() );
 setTextInsertionStyle( newStyleObject );
```

**Comment by garybentley** [comment]
Thanks, I should have noticed that was missing.  I'm using that technique for bolding a chunk of text.

I'm now using the new object for the insertion style but it's not using that style.  That is even if I switch on bold the next character I type isn't bolded.  I have checked that the style is correct.  Any ideas?  Or better still do you have some test code that you know works and then I base my code on that.

**Comment by Jugen** [comment]
Then you probably have to switch off "useInitialStyle" with `area.setUseInitialStyleForInsertion( false );`

At the moment the code prefers to "useInitialStyle" before using the "insertionStyle":
```java
        if ( useInitialStyleForInsertion.get() ) {
            return initialTextStyle;
        } else if ( insertionTextStyle != null ) {
            return insertionTextStyle;
        } else {
            return content.getStyleAtPosition(pos);
        }
```
but I wonder if it shouldn't rather be the other way round like this:
```java
       if ( insertionTextStyle != null ) {
           return insertionTextStyle;
        } else if( useInitialStyleForInsertion.get() ) {
            return initialTextStyle;
        } else {
            return content.getStyleAtPosition(pos);
        }
```

**Comment by garybentley** [comment]
Personally I think it should be:

insertionTextStyle else styleAtPosition else initialStyle

I'm not entirely sure what the point of the initial style is.  In my view methods like insertText, insert, replaceText and appendText should have a "style" argument that is used when inserting/replacing and if not present then the style should default to whatever the current style is at the insertion/replacement position, then, ultimately, have a default style that is used when nothing else is available.

**Comment by Jugen** [comment]
>  In my view methods like insertText, insert, replaceText and appendText should have a "style" argument that is used when inserting/replacing ....

See newly added API from [#868](https://github.com/FXMisc/RichTextFX/issues/868#issuecomment-555014379) "Append text with different style" with PR #869 "Added convenience API to InlineCss and StyleClassed TextAreas".

**Pull request merged**
